### ISSUE TITLE
Services do not work on master deployments 

### ISSUE THREAD

**Issue by wziajka** [cyfronet-fid/marketplace#188]
In current master deploy (version: master 8d3332effd72a19052401a1d3852ffe00f0102c2) services do not work, server returns 500 error code. 

Logs 

I, [2018-10-03T12:40:23.850004 #1]  INFO -- : [88325369-df24-455d-9f3b-77bd0b33f2e3] Started GET "/services" for 149.156.10.86 at 2018-10-03 12:40:23 +0000
I, [2018-10-03T12:40:23.851100 #1]  INFO -- : [88325369-df24-455d-9f3b-77bd0b33f2e3] Processing by ServicesController#index as HTML
I, [2018-10-03T12:40:23.852622 #1]  INFO -- : [88325369-df24-455d-9f3b-77bd0b33f2e3]   Rendering services/index.html.haml within layouts/application
D, [2018-10-03T12:40:23.854273 #1] DEBUG -- : [88325369-df24-455d-9f3b-77bd0b33f2e3]   Category Exists (0.4ms)  SELECT  1 AS one FROM "categories" WHERE "categories"."ancestry" IS NULL LIMIT $1  [["LIMIT", 1]]
D, [2018-10-03T12:40:23.855081 #1] DEBUG -- : [88325369-df24-455d-9f3b-77bd0b33f2e3]   Category Load (0.5ms)  SELECT "categories".* FROM "categories" WHERE "categories"."ancestry" IS NULL
I, [2018-10-03T12:40:23.858287 #1]  INFO -- : [88325369-df24-455d-9f3b-77bd0b33f2e3]   Rendered collection of categories/_subcategory.html.haml [30 times] (2.5ms)
I, [2018-10-03T12:40:23.858414 #1]  INFO -- : [88325369-df24-455d-9f3b-77bd0b33f2e3]   Rendered categories/_subcategories.html.haml (5.5ms)
D, [2018-10-03T12:40:23.859428 #1] DEBUG -- : [88325369-df24-455d-9f3b-77bd0b33f2e3]   Service Load (0.6ms)  SELECT  "services".* FROM "services" LIMIT $1 OFFSET $2  [["LIMIT", 30], ["OFFSET", 0]]
I, [2018-10-03T12:40:23.861880 #1]  INFO -- : [88325369-df24-455d-9f3b-77bd0b33f2e3]   Rendered collection of services/_service.html.haml [18 times] (1.7ms)
I, [2018-10-03T12:40:23.862020 #1]  INFO -- : [88325369-df24-455d-9f3b-77bd0b33f2e3]   Rendered services/_services.html.haml (3.4ms)
I, [2018-10-03T12:40:23.862146 #1]  INFO -- : [88325369-df24-455d-9f3b-77bd0b33f2e3]   Rendered services/index.html.haml within layouts/application (9.4ms)
I, [2018-10-03T12:40:23.862325 #1]  INFO -- : [88325369-df24-455d-9f3b-77bd0b33f2e3] Completed 500 Internal Server Error in 11ms (ActiveRecord: 1.5ms)
D, [2018-10-03T12:40:23.862438 #1] DEBUG -- : [88325369-df24-455d-9f3b-77bd0b33f2e3] undefined method `name' for nil:NilClass excluded from capture: DSN not set
F, [2018-10-03T12:40:23.863403 #1] FATAL -- : [88325369-df24-455d-9f3b-77bd0b33f2e3]   
F, [2018-10-03T12:40:23.863474 #1] FATAL -- : [88325369-df24-455d-9f3b-77bd0b33f2e3] ActionView::Template::Error (undefined method `name' for nil:NilClass):
F, [2018-10-03T12:40:23.863631 #1] FATAL -- : [88325369-df24-455d-9f3b-77bd0b33f2e3]      6:       .mb-3= service.tagline
[88325369-df24-455d-9f3b-77bd0b33f2e3]      7:       %p.small.float-left.mr-4
[88325369-df24-455d-9f3b-77bd0b33f2e3]      8:         Provided by
[88325369-df24-455d-9f3b-77bd0b33f2e3]      9:         = link_to service.provider.name, service.provider
[88325369-df24-455d-9f3b-77bd0b33f2e3]     10: 
[88325369-df24-455d-9f3b-77bd0b33f2e3]     11:       %p.small
[88325369-df24-455d-9f3b-77bd0b33f2e3]     12:         Available for SME only within 1 day
F, [2018-10-03T12:40:23.863692 #1] FATAL -- : [88325369-df24-455d-9f3b-77bd0b33f2e3]   
F, [2018-10-03T12:40:23.863743 #1] FATAL -- : [88325369-df24-455d-9f3b-77bd0b33f2e3] app/views/services/_service.html.haml:9:in `_app_views_services__service_html_haml___1586420588106990979_47194632213960'
[88325369-df24-455d-9f3b-77bd0b33f2e3] app/views/services/_services.html.haml:2:in `_app_views_services__services_html_haml___2319856457440282093_47194636061460'
[88325369-df24-455d-9f3b-77bd0b33f2e3] app/views/services/index.html.haml:59:in `_app_views_services_index_html_haml__4492606928797819011_47194623942320'

**Comment by martaswiatkowska** [comment]
I have problem with db:seed / dev:rake and I cannot generate services from yaml @goreck888 ??   

exception:
ActiveRecord::AssociationTypeMismatch: Category(#77566600) expected, got nil which is an instance of NilClass(#15310380)
/home/marta/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/associations/association.rb:238:in `raise_on_type_mismatch!'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:244:in `block in replace'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:244:in `each'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:244:in `replace'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/associations/collection_association.rb:41:in `writer'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/associations/builder/association.rb:116:in `categories='
/home/marta/.rvm/gems/ruby-2.5.1/gems/activemodel-5.2.0/lib/active_model/attribute_assignment.rb:51:in `public_send'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activemodel-5.2.0/lib/active_model/attribute_assignment.rb:51:in `_assign_attribute'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activemodel-5.2.0/lib/active_model/attribute_assignment.rb:44:in `block in _assign_attributes'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activemodel-5.2.0/lib/active_model/attribute_assignment.rb:43:in `each'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activemodel-5.2.0/lib/active_model/attribute_assignment.rb:43:in `_assign_attributes'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/attribute_assignment.rb:23:in `_assign_attributes'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activemodel-5.2.0/lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/core.rb:314:in `initialize'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/inheritance.rb:66:in `new'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/inheritance.rb:66:in `new'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/persistence.rb:35:in `create'
/home/marta/Projekty/marketplace/lib/tasks/dev.rake:14:in `block (3 levels) in <top (required)>'
/home/marta/Projekty/marketplace/lib/tasks/dev.rake:13:in `times'
/home/marta/Projekty/marketplace/lib/tasks/dev.rake:13:in `block (2 levels) in <top (required)>'
/home/marta/Projekty/marketplace/db/seeds.rb:42:in `<top (required)>'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
/home/marta/.rvm/gems/ruby-2.5.1/gems/railties-5.2.0/lib/rails/engine.rb:551:in `load_seed'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/home/marta/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <top (required)>'
/home/marta/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/marta/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
/home/marta/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by martaswiatkowska** [comment]
No, error does not appear anymore
