### ISSUE TITLE
Random ordering failing tests

### ISSUE THREAD

**Issue by mkasztelnik** [cyfronet-fid/marketplace#239]
**Describe the bug**
```
  1) Service filtering and sorting selecting sorting will set query param and preserve existing ones
     Failure/Error: expect(page.body.index("DDDD Something 3")).to be < page.body.index("DDDD Something 2")
     
       expected: < 15467
            got:   nil
     # ./spec/features/service_spec.rb:67:in `block (2 levels) in <main>'

  2) Service filtering and sorting clicking filter button in side bar will preserve existing query params
     Failure/Error: expect(page.body.index("DDDD Something 1")).to be < page.body.index("DDDD Something 2")
     
       expected: < 15465
            got:   nil
     # ./spec/features/service_spec.rb:53:in `block (2 levels) in <main>'

```

**To Reproduce**
This is a random failing test. E.g. it occurs for me with `58921` seed.

**Comment by mkasztelnik** [comment]
There is additional huge problem `sleep(1)` - this definitely should be removed.

**Comment by mkasztelnik** [comment]
This is most probably connected with the fact that the same elasticsearch instance is used for `development` and `test` environments. 

There are multiple ways how to deal with such problem, e.g. https://medium.com/@rowanoulton/testing-elasticsearch-in-rails-22a3296d989 - this is not convenient for us since all tests which use service requires elasticsearch. The other option is to look at database cleaner `:truncate` strategy and measure how it will slow down our test suit.
