### ISSUE TITLE
Update project dependencies 

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#776]
We have some dependencies that can cause security issues in long term.
Update the versions of libraries with high/critical severity alerts and try to bump all modarate and lower in cases in which update doesn't cause major issues.  

![image.png](https://images.zenhubusercontent.com/5b0fe7c84b5806bc2bd57e5c/9aaefab0-f2d5-4c49-87f9-c190206774d7)

**Comment by mkasztelnik** [comment]
I started this job, but the upgrade is of the gems is quite complicated. The first issue discovered is that we have 2 URL validation. First in `validate_url` (added to the project as `openid_connect` dependency, second in `app/validators/url_validator.rb`. The second validator is not used and should be removed. After the upgrade, there is a problem with the validation, which is solved by https://github.com/perfectline/validates_url/commit/a15572694970c936ae164f6b357c1d518b898656. 

Next there is a problem with following specs:

```
  1) Service ordering as logged in user Voucher ID input should not be visible if 'request voucher' radio is set
     Failure/Error: expect(page).to_not have_text("Voucher ID")
       expected not to find text "Voucher ID" in "Cancel order and quit\nNext\nservice 9\nservice 9 tagline\nService configuration\nSummary\nService configuration\nWe need more information about your request. We will be able to process your request quicker if the form is filled with as much detail as possible.\nVoucher\nI have a voucher, I want to use it I want to ask for vouchers\nVoucher ID *\nMy projects\nYou can organize your services in projects. Add this service to a specific project or create a new one.\nProject *\nServices\nAdd new project\nUsage\nCustomer typology *\nSingle user\nRepresenting a research community\nRepresenting a private company\nRepresenting a project\nUser group name *\nProject name *\nProject website url *\nCompany name *\nCompany website url *\nAccess reason *\nAdditional information\nResearch area *\nresearch area 13\nresearch area 14\nAffiliation\nAffiliation *\norganization 5\nClick here to create a new affilition\nNext\nCopyright 2018 - All right reserved privacy policy\nAbout\nEOSC\nEOSC Doers\nEOSC Projects\nFunding Opportunities\nMarketplace\nFAQs\nContact us\nGovernance\nEOSC Governance\nRules of participation\nBest Practices\nServices & Resources\nSharing & Discovery\nProcessing & Analysis\nData Management\nCompute\nStorage\nNetworking\nTraining & Support\nSecurity & Operations\nPolicy\nEC Documents\nEurope\nMember States\nEOSC IN PRACTICE\nUse Cases\nOpen Call\nMedia\nNews\nForthcoming events\nPast Events\nMARKETPLACE\nAbout\nAll Services\ncategory 9\nFor providers\nThe EOSC portal is been jointly developed and maintained by the EOSC-hub, eInfraCentral and OpenAIRE-Advance projects funded by the Euopean\nUnion’s Horizon 2020 research and innovation programme with contribution of the European Commission\n2018 EOSC Portal\n×\nClose New"
     # ./spec/features/order_spec.rb:397:in `block (3 levels) in <main>'

  2) Service filtering and sorting multiselect shows checked element regardless of toggle state
     Failure/Error: expect(page).to have_selector("input[name='providers[]']", count: 5)
       expected to find visible css "input[name='providers[]']" 5 times, found 7 matches: "", "", "", "", "", "", ""
     # ./spec/features/service_spec.rb:282:in `block (2 levels) in <main>'

  3) Service filtering and sorting multiselect toggle
     Failure/Error: expect(page).to have_selector("input[name='providers[]']:not([style*=\"display: none\"])", count: 5)
       expected to find visible css "input[name='providers[]']:not([style*=\"display: none\"])" 5 times, found 7 matches: "", "", "", "", "", "", ""
     # ./spec/features/service_spec.rb:272:in `block (2 levels) in <main>'

  4) Service filtering and sorting multiselect does not show toggle button if everything is shown
     Failure/Error: expect(page).to have_selector("input[name='providers[]']", count: 5)
       expected to find visible css "input[name='providers[]']" 5 times, found 7 matches: "", "", "", "", "", "", ""
     # ./spec/features/service_spec.rb:293:in `block (2 levels) in <main>'
```

I need to track what changed in (most probably) `capybara`/webdrivers` gem and discover why invisible elements are returned by the selector.

See #777 for details
